name = "neosphere"
compatibility_date = "2024-04-05"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "neosphere_assets"
bucket_name = "neosphere-assets"

[[d1_databases]]
binding = "DB"
database_name = "neosphere-db"
database_id = "4ec14f0d-7ce9-4ae7-8469-3074b38fe915"
